accounts/urls.py
from django.urls import path
from . import views

# URL 분리시에 urlpatterns를 선언하지 않으면 에러 발생
app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('complete_login/', views.complete_login, name='complete_login'),
]

admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('logins_front/', include("logins_front.urls"))
]

articles/urls.py
from django.urls import path
from . import views

# URL 분리시에 urlpatterns를 선언하지 않으면 에러 발생
app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
]

logins_front/urls.py
from django.urls import path
from . import views

app_name = "logins_front"
urlpatterns = [
    path('', views.index, name='index'),
]

ssafy_yam/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
# 대체하기 1단계 : AbstractUser를 상속받는 새로운 User 클래스 정의
class User(AbstractUser):
    pass

articles/models.py
from django.db import models

# Create your models here.
# model class 설계도 초안을 작성하는 것
# 1. 필드 이름 (클래스 변수명)
# 2. 필드의 데이터 타입 (model field)
# 3. 필드의 제약조건 (model field 키워드 인자)
class Date(models.Model):
    lunch_date = models.DateTimeField(auto_now=False)


class MainLunch(models.Model):
    title = models.CharField(max_length=10)
    content_20_korean_menu = models.TextField()
    content_20_special_menu = models.TextField()   
    
    
class SubLunch(models.Model):
    title = models.CharField(max_length=10)
    content_10_lunchbox_menu = models.TextField()
    content_10_sandwich_menu = models.TextField()
    content_10_salad_menu = models.TextField()

logins_front/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, ReadOnlyPasswordHashField
from django import forms

class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label= False,
        widget= forms.TextInput(
            attrs={
                'class': 'input-box'
            }
        )
    )

    password = forms.CharField(
        label= False,
        widget = forms.PasswordInput(
            attrs={
                'class': 'input-box'
            }
        )
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login


# Create your views here.
def login(request):
    # 요청 메서드가 POST라면, 사용자 입력 데이터를 활용해 로그인을 진행
    if request.method == 'POST':
        # AuthenticationForm은 ModelForm이 아니라 Form
        # 사용자가 입력하는 데이터를 DB에 저장하지 않기 때문
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            # 로그인을 진행 (세션을 생성)
            auth_login(request, user)
            return redirect('accounts:complete_login')
    # 요청 메서드가 POST가 아니라면, login 페이지를 응답
    context = {
        'form': form,
    } 
    return render(request, 'articles/index.html', context)
    # return redirect('articles:index')
    
def complete_login(request):
    return render(request,'accounts/complete_login.html' )

articles/views.py
from django.shortcuts import render
from .models import Date, MainLunch, SubLunch
from accounts.forms import CustomAuthenticationForm



# Create your views here.
def index(request):
    # DB에서 전체 게시글을 조회 후

    dates = Date.objects.all()
    mainlunchs = MainLunch.objects.all()
    sublunchs = SubLunch.objects.all()
    form = CustomAuthenticationForm()
    # 메인 페이지를 응답 (render)
    # context는 다름 이름이여도 상관 없음(단, 반드시 딕셔너리여야 함)
    if mainlunchs or sublunchs:
        context = {
            'dates': dates,
            'mainlunchs': mainlunchs,
            'sublunchs': sublunchs,
            'form': form,
            'success' : True,
        }
    else:
       context = {
       
            'success' : False,
            'message': '메뉴가 없습니다.'
        } 
    
    return render(request, 'articles/index.html', context)



# context = {
#     'dates': dates
    
# }

# dates = [
#     {
#     'id': 1
#     'lunch_date': '2024'
#     },
    
#     {
#     'id': 2
#     'lunch_date': '2024'
#     },
# ]

logins_front/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    print('test')
    return render(request, 'logins_front/login.html')

accounts/templates/accounts/complete_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap')
  </style>
</head>
<body>
  <div class="top"></div>

  <div class="contentbox gowun-dodum-regular">
    <div class="vertical_center">
      <div>
        <h2 class="text_center">{{ user.username }}님, 3반에 오신 것을 환영합니다🍙</h2>
        <h2 class="text_center">password가 들키지 않도록 조심해 주세요!</h2>
      </div>
      <div class="container">
        <a href="{% url "articles:index" %}" class="button center bold grey">홈으로 돌아가기</a>
      </div>
    </div>
  </div>
</body>
</html>

articles/templates/articles/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{% static 'articles/css/index.css' %}">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Gowun+Dodum&display=swap')
  </style>
</head>
<body>
  <div class="top">
  </div>

  <div class="container gowun-dodum-regular">
    <div class="login-box"> 
      <div>
        <p>싸피로고</p>
      </div>
      <form action="{% url "accounts:login" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인" class="login-button gowun-dodum-regular">
      </form>
    </div>
        
    <div class="menu-box smaller">
      <div>
        {% for item in mainlunchs %}
            <p>{{ item.title }}</p>
            <p>한식 : {{ item.content_20_korean_menu }}</p>
            <p>특별식 : {{ item.content_20_special_menu }}</p>
        {% endfor %}
        <hr>
        {% for item in sublunchs %}
            <p>{{ item.title }}</p>
            <p>도시락 : {{ item.content_10_lunchbox_menu }}</p>
            <p>샌드위치 : {{ item.content_10_sandwich_menu }}</p>
            <p>샐러드 : {{ item.content_10_salad_menu }}</p>
        {% endfor %}
      </div>
    </div>
  </div>
</body>
</html>

logins_front/templates/logins_front/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link rel="stylesheet" href="{% static "logins_front/css/login.css" %}">
</head>
<body>
  <div class="top">
  </div>
  <div class="container centerize"> 
    <div>
      <p>싸피로고</p>
      아이디: <input type="text">
      비밀번호: <input type="password">
      <input type="button" value="로그인">
    </div>
      
    <div class="menu_box">
      {% comment %} 오른쪽 급식정보로딩페이지 {% endcomment %}
    </div>
  </div>
</body>
</html>